### PR TITLE
Added DNF package manager

### PR DESCRIPTION
**Pull request by l1a**
Added dnf.rs, changed mod.rs

### CODE REVIEW

**Comment by tversteeg** [comment]
Thanks a lot for the PR!

**Comment by l1a** [comment]
Sure. Have to be a little later today...

**Comment by l1a** [comment]
Updated the README. 

I haven't looked into it yet, but the "first time" process seems to be a little rough. If you start with no emplace.toml and no .emplace RON file but an empty source repo (just a "git init"), the first addition fails with either a "no file" or "format incorrect" type message if you create an empty .emplace file. Just an observation.

**Comment by tversteeg** [comment]
Thanks for the addition and the observation, I'll look into that.

**Comment by tversteeg** [comment]
@all-contributors please add @l1a  for platform

**Pull request merged**
