### PR TITLE
Fix polling of installtion programm. Fix yay

### PR DESCRIPTION
**Pull request by 0xd34b33f**
Checking, that package manager is installed was donein strange way.  
For example, checking, that yay is installed will produce n `[sudo] password for username: `,
where n is number of pakages to install. 
In addition, fixed some issues with yay.

### CODE REVIEW

**Comment by tversteeg** [comment]
Thanks for the PR but I'm going to postpone merging this since I'm currently busy refactoring that part that it's touching. It would cause me some annoying merge conflicts when I accept it now.

**Comment by 0xd34b33f** [comment]
Haven't notice it :(

**Comment by tversteeg** [comment]
My bad, I forgot to push the branch.

**Comment by 0xd34b33f** [comment]
If you are doing it because of slowness of regex, think twice: 13.443626ms spent on catch. On my mind, it's really little time and waiting for git pull every time, when some installation is captured is annoying a lot more.

**Comment by tversteeg** [comment]
Oh no, the performance of the regexes isn't what bothers me the most. What bothers me is that the implementation details of a new package manager are spread over multiple files. And the regexes themselves are not generically handling common things.

**Comment by tversteeg** [comment]
There's still a lot of merge conflicts, maybe it's easier to start over?

**Comment by 0xd34b33f** [comment]
Ok, give me some time for it

**Comment by 0xd34b33f** [comment]
@tversteeg everything is fixed

**Pull request merged**
