### PR TITLE
Add Cargo.lock

### PR DESCRIPTION
**Pull request by filalex77**
This is an executable, so it makes sense to have it checked in. Repositories
like [NixOS/nixpkgs](https://github.com/NixOS/nixpkgs) require `Cargo.lock` to
be present in order to package the software.

---
This change is [Reviewable](https://reviewable.io/reviews/tversteeg/emplace/2)

### CODE REVIEW

**Comment by tversteeg** [comment]
Thanks a lot for this PR!

**Comment by filalex77** [comment]
@tversteeg You're welcome! Can we get a patch release, so I can package emplace for nixpkgs? Thanks!

**Comment by tversteeg** [comment]
@filalex77 That's awesome of you, thanks a lot! I just made a patch release.

**Comment by tversteeg** [comment]
@all-contributors please add @filalex77  for code

**Comment by filalex77** [comment]
@tversteeg Can you add me for packaging as well? I'm maintaining `emplace` in [NixOS/nixpkgs](https://github.com/NixOS/nixpkgs).

**Comment by tversteeg** [comment]
I was looking for that but there isn't really an emoji key for packaging: https://allcontributors.org/docs/en/emoji-key

What key do you suggest?

**Comment by lberrymage** [comment]
They have one for packaging called "`platform`".

**Comment by tversteeg** [comment]
@all-contributors please add @filalex77 for platform

**Comment by filalex77** [comment]
@tversteeg Thanks, I appreciate it!

**Pull request merged**
